"""
integration_example.py – Generic FlowDelta integration template.

Copy this file into any Python project and adapt the three clearly-marked
sections to your own code.  No changes to FlowDelta itself are required.

Run from your project root after installing FlowDelta::

    pip install flowdelta         # or: pip install -e /path/to/FlowDelta
    python integration_example.py

What you get:
  • A persisted trace + delta in     .flowdelta/runs/
  • A runnable pytest file in        generated_tests/test_<flow_id>.py
  • A dashboard at                   http://127.0.0.1:8765  (flowdelta dashboard)
"""

from __future__ import annotations

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 1 — Import FlowDelta
# ─────────────────────────────────────────────────────────────────────────────
from flowdelta import FlowDelta


# ─────────────────────────────────────────────────────────────────────────────
# SECTION 2 — Configure FlowDelta for your project
#
# All parameters have sensible defaults:
#   store_path  → ".flowdelta/runs"  (where traces/deltas are stored)
#   output_dir  → "generated_tests" (where pytest files are written)
#
# Pass config_path only if you have a flowdelta.yaml (created by
# `flowdelta init`).  It is completely optional.
# ─────────────────────────────────────────────────────────────────────────────
fd = FlowDelta(
    # src_dir="src/",             # optional — point at your source tree
    # config_path="flowdelta.yaml",  # optional — generated by `flowdelta init`
    store_path=".flowdelta/runs",
    output_dir="generated_tests",
)


# ─────────────────────────────────────────────────────────────────────────────
# SECTION 3 — Replace this stub with YOUR application pipeline
#
# Below is a self-contained demo; swap it out entirely.
# ─────────────────────────────────────────────────────────────────────────────

def validate(data: dict) -> dict:
    """Validate input fields."""
    if not data.get("user_id"):
        raise ValueError("user_id is required")
    return {**data, "validated": True}


def enrich(data: dict) -> dict:
    """Enrich data with derived fields."""
    return {**data, "score": len(data["user_id"]) * 10}


def persist(data: dict) -> str:
    """Simulate persisting and return a record ID."""
    return f"REC-{data['user_id'].upper()}-{data['score']}"


def my_pipeline(user_id: str, payload: dict) -> str:
    """Top-level pipeline entry point — replace with your own function."""
    data = validate({"user_id": user_id, **payload})
    enriched = enrich(data)
    record_id = persist(enriched)
    return record_id


# ─────────────────────────────────────────────────────────────────────────────
# SECTION 4 — Observe the pipeline
#
# fd.observe() runs your function, traces state across all called functions,
# computes deltas, and generates a pytest file — all in one call.
#
# Options:
#   flow_id         — name for this flow (defaults to function name)
#   watch_functions — which functions to trace (auto-detected when omitted)
#   golden=True     — mark this run as the regression baseline
#   generate_tests  — set False to skip test file generation
# ─────────────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    result = fd.observe(
        my_pipeline,
        "alice",
        {"region": "US"},
        flow_id="my-pipeline",
        # watch_functions={"my_pipeline", "validate", "enrich", "persist"},
        golden=True,
        generate_tests=True,
    )
    print(f"Result: {result}")
    print("Traces  → .flowdelta/runs/")
    print("Tests   → generated_tests/test_my-pipeline.py")
    print("Run     : pytest generated_tests/")
    print("Dashboard: flowdelta dashboard")


# ─────────────────────────────────────────────────────────────────────────────
# ALTERNATIVE: Use the @track decorator instead of fd.observe()
#
#   from flowdelta import track
#
#   @track(flow_id="my-pipeline", golden=True)
#   def my_pipeline(user_id: str, payload: dict) -> str:
#       ...
#
#   my_pipeline("alice", {"region": "US"})  # FlowDelta kicks in automatically
# ─────────────────────────────────────────────────────────────────────────────
